// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	cache "bitbucket.org/moladinTech/go-lib-common/cache"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cacher is an autogenerated mock type for the Cacher type
type Cacher struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *Cacher) Delete(ctx context.Context, key cache.Key) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cache.Key) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, key, dest
func (_m *Cacher) Get(ctx context.Context, key cache.Key, dest interface{}) error {
	ret := _m.Called(ctx, key, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cache.Key, interface{}) error); ok {
		r0 = rf(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: ctx, data, duration
func (_m *Cacher) Set(ctx context.Context, data cache.Data, duration time.Duration) error {
	ret := _m.Called(ctx, data, duration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cache.Data, time.Duration) error); ok {
		r0 = rf(ctx, data, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCacher interface {
	mock.TestingT
	Cleanup(func())
}

// NewCacher creates a new instance of Cacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCacher(t mockConstructorTestingTNewCacher) *Cacher {
	mock := &Cacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
