// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FuncConvert is an autogenerated mock type for the FuncConvert type
type FuncConvert struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *FuncConvert) Execute(_a0 interface{}) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewFuncConvert interface {
	mock.TestingT
	Cleanup(func())
}

// NewFuncConvert creates a new instance of FuncConvert. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFuncConvert(t mockConstructorTestingTNewFuncConvert) *FuncConvert {
	mock := &FuncConvert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
