// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	sqlx "github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// TxFunc is an autogenerated mock type for the TxFunc type
type TxFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: tx
func (_m *TxFunc) Execute(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTxFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxFunc creates a new instance of TxFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxFunc(t mockConstructorTestingTNewTxFunc) *TxFunc {
	mock := &TxFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
