// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	data_source "bitbucket.org/moladinTech/go-lib-common/data_source"
	mock "github.com/stretchr/testify/mock"
)

// TxOpt is an autogenerated mock type for the TxOpt type
type TxOpt struct {
	mock.Mock
}

// Execute provides a mock function with given fields: t
func (_m *TxOpt) Execute(t *data_source.TransactionRunner) {
	_m.Called(t)
}

type mockConstructorTestingTNewTxOpt interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxOpt creates a new instance of TxOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxOpt(t mockConstructorTestingTNewTxOpt) *TxOpt {
	mock := &TxOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
