// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IMiddlewareTracer is an autogenerated mock type for the IMiddlewareTracer type
type IMiddlewareTracer struct {
	mock.Mock
}

// Tracer provides a mock function with given fields:
func (_m *IMiddlewareTracer) Tracer() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewIMiddlewareTracer interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMiddlewareTracer creates a new instance of IMiddlewareTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMiddlewareTracer(t mockConstructorTestingTNewIMiddlewareTracer) *IMiddlewareTracer {
	mock := &IMiddlewareTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
